### ISSUE TITLE
Missing Parameters

### ISSUE THREAD

**Issue by mcroni** [centrifugal/cent#19]
`__init__() missing 1 required positional argument: 'secret'` . It seems secret is needed when passing parameters for `Client`. I added this and i get an `wrong status code: 404` when i try to test publish

**Comment by FZambia** [comment]
@mcroni hello, which version are you using? Since we don't have any word `secret` in codebase. I suppose you are using Cent v2 which is old version that works with Centrifugo v1. For actual Centrifugo v2 you should use [latest Cent library version](https://github.com/centrifugal/cent/releases/tag/v3.0.1)

**Comment by mcroni** [comment]
@FZambia thanks for this,  i did a `pip install --upgrade` and it works good
